"""initial cowork reporting schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-09-01

Creates the full star schema from the ORM metadata. Using ``create_all`` keeps
this initial migration in lockstep with ``shared/models.py``; subsequent schema
changes get their own autogenerated revisions.
"""
from __future__ import annotations

from alembic import op

import shared.models  # noqa: F401 - registers tables on Base.metadata
from shared.db import Base

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    Base.metadata.create_all(bind=bind)


def downgrade() -> None:
    bind = op.get_bind()
    Base.metadata.drop_all(bind=bind)
